// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/agent/v1/runtime.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{0}
}

type Workspace struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RepositoryRef    string                 `protobuf:"bytes,1,opt,name=repository_ref,json=repositoryRef,proto3" json:"repository_ref,omitempty"`
	BaseCommit       string                 `protobuf:"bytes,2,opt,name=base_commit,json=baseCommit,proto3" json:"base_commit,omitempty"`
	IsolationProfile string                 `protobuf:"bytes,3,opt,name=isolation_profile,json=isolationProfile,proto3" json:"isolation_profile,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Workspace) GetRepositoryRef() string {
	if x != nil {
		return x.RepositoryRef
	}
	return ""
}

func (x *Workspace) GetBaseCommit() string {
	if x != nil {
		return x.BaseCommit
	}
	return ""
}

func (x *Workspace) GetIsolationProfile() string {
	if x != nil {
		return x.IsolationProfile
	}
	return ""
}

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *Input) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TaskSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProjectId            string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	IdempotencyKey       string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Engine               string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	RuntimeProfile       string                 `protobuf:"bytes,4,opt,name=runtime_profile,json=runtimeProfile,proto3" json:"runtime_profile,omitempty"`
	Model                string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	CredentialRef        string                 `protobuf:"bytes,6,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	Workspace            *Workspace             `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Input                *Input                 `protobuf:"bytes,8,opt,name=input,proto3" json:"input,omitempty"`
	PolicyRef            string                 `protobuf:"bytes,9,opt,name=policy_ref,json=policyRef,proto3" json:"policy_ref,omitempty"`
	RequiredCapabilities []string               `protobuf:"bytes,10,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	SessionRef           string                 `protobuf:"bytes,11,opt,name=session_ref,json=sessionRef,proto3" json:"session_ref,omitempty"`
	ParentTaskId         string                 `protobuf:"bytes,12,opt,name=parent_task_id,json=parentTaskId,proto3" json:"parent_task_id,omitempty"`
	TimeoutSeconds       int64                  `protobuf:"varint,13,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	AcceptanceProfile    string                 `protobuf:"bytes,14,opt,name=acceptance_profile,json=acceptanceProfile,proto3" json:"acceptance_profile,omitempty"`
	Priority             int32                  `protobuf:"varint,15,opt,name=priority,proto3" json:"priority,omitempty"`
	ProviderRef          string                 `protobuf:"bytes,16,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *TaskSpec) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TaskSpec) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *TaskSpec) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *TaskSpec) GetRuntimeProfile() string {
	if x != nil {
		return x.RuntimeProfile
	}
	return ""
}

func (x *TaskSpec) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TaskSpec) GetCredentialRef() string {
	if x != nil {
		return x.CredentialRef
	}
	return ""
}

func (x *TaskSpec) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *TaskSpec) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TaskSpec) GetPolicyRef() string {
	if x != nil {
		return x.PolicyRef
	}
	return ""
}

func (x *TaskSpec) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *TaskSpec) GetSessionRef() string {
	if x != nil {
		return x.SessionRef
	}
	return ""
}

func (x *TaskSpec) GetParentTaskId() string {
	if x != nil {
		return x.ParentTaskId
	}
	return ""
}

func (x *TaskSpec) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *TaskSpec) GetAcceptanceProfile() string {
	if x != nil {
		return x.AcceptanceProfile
	}
	return ""
}

func (x *TaskSpec) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskSpec) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type TaskRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRef) Reset() {
	*x = TaskRef{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRef) ProtoMessage() {}

func (x *TaskRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRef.ProtoReflect.Descriptor instead.
func (*TaskRef) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *TaskRef) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type Task struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State             string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	AttemptId         string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Spec              *TaskSpec              `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	LastSeq           int64                  `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result            string                 `protobuf:"bytes,8,opt,name=result,proto3" json:"result,omitempty"`
	SessionRef        string                 `protobuf:"bytes,9,opt,name=session_ref,json=sessionRef,proto3" json:"session_ref,omitempty"`
	WorkerId          string                 `protobuf:"bytes,10,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CreatedAtMs       int64                  `protobuf:"varint,11,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	UpdatedAtMs       int64                  `protobuf:"varint,12,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	SchedulingBlocker string                 `protobuf:"bytes,13,opt,name=scheduling_blocker,json=schedulingBlocker,proto3" json:"scheduling_blocker,omitempty"`
	Existing          bool                   `protobuf:"varint,14,opt,name=existing,proto3" json:"existing,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Task) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Task) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Task) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Task) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Task) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Task) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Task) GetSessionRef() string {
	if x != nil {
		return x.SessionRef
	}
	return ""
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Task) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *Task) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *Task) GetSchedulingBlocker() string {
	if x != nil {
		return x.SchedulingBlocker
	}
	return ""
}

func (x *Task) GetExisting() bool {
	if x != nil {
		return x.Existing
	}
	return false
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AfterSeq      int64                  `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *WatchRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *WatchRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ControlId     string                 `protobuf:"bytes,2,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelRequest) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ControlId     string                 `protobuf:"bytes,2,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Input         *Input                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ControlRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ControlRequest) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *ControlRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ControlRequest) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	EventId       string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	WorkerSeq     int64                  `protobuf:"varint,5,opt,name=worker_seq,json=workerSeq,proto3" json:"worker_seq,omitempty"`
	Seq           int64                  `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	RecordedAtMs  int64                  `protobuf:"varint,9,opt,name=recorded_at_ms,json=recordedAtMs,proto3" json:"recorded_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Event) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Event) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetWorkerSeq() int64 {
	if x != nil {
		return x.WorkerSeq
	}
	return 0
}

func (x *Event) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *Event) GetRecordedAtMs() int64 {
	if x != nil {
		return x.RecordedAtMs
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThroughSeq    int64                  `protobuf:"varint,1,opt,name=through_seq,json=throughSeq,proto3" json:"through_seq,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetThroughSeq() int64 {
	if x != nil {
		return x.ThroughSeq
	}
	return 0
}

func (x *Ack) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Runtime struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Profile         string                 `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Models          []string               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	Credentials     []string               `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Capabilities    []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Repositories    []string               `protobuf:"bytes,6,rep,name=repositories,proto3" json:"repositories,omitempty"`
	Policies        []string               `protobuf:"bytes,7,rep,name=policies,proto3" json:"policies,omitempty"`
	Verifiers       []string               `protobuf:"bytes,8,rep,name=verifiers,proto3" json:"verifiers,omitempty"`
	TemplateDigests map[string]string      `protobuf:"bytes,9,rep,name=template_digests,json=templateDigests,proto3" json:"template_digests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *Runtime) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Runtime) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Runtime) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Runtime) GetCredentials() []string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Runtime) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Runtime) GetRepositories() []string {
	if x != nil {
		return x.Repositories
	}
	return nil
}

func (x *Runtime) GetPolicies() []string {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *Runtime) GetVerifiers() []string {
	if x != nil {
		return x.Verifiers
	}
	return nil
}

func (x *Runtime) GetTemplateDigests() map[string]string {
	if x != nil {
		return x.TemplateDigests
	}
	return nil
}

type WorkerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Epoch         string                 `protobuf:"bytes,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Slots         int32                  `protobuf:"varint,3,opt,name=slots,proto3" json:"slots,omitempty"`
	Runtimes      []*Runtime             `protobuf:"bytes,4,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHello) Reset() {
	*x = WorkerHello{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHello) ProtoMessage() {}

func (x *WorkerHello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHello.ProtoReflect.Descriptor instead.
func (*WorkerHello) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *WorkerHello) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHello) GetEpoch() string {
	if x != nil {
		return x.Epoch
	}
	return ""
}

func (x *WorkerHello) GetSlots() int32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *WorkerHello) GetRuntimes() []*Runtime {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type WorkerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Slots         int32                  `protobuf:"varint,3,opt,name=slots,proto3" json:"slots,omitempty"`
	Active        int32                  `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	LastSeenMs    int64                  `protobuf:"varint,5,opt,name=last_seen_ms,json=lastSeenMs,proto3" json:"last_seen_ms,omitempty"`
	Runtimes      []*Runtime             `protobuf:"bytes,6,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *WorkerStatus) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *WorkerStatus) GetSlots() int32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *WorkerStatus) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *WorkerStatus) GetLastSeenMs() int64 {
	if x != nil {
		return x.LastSeenMs
	}
	return 0
}

func (x *WorkerStatus) GetRuntimes() []*Runtime {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type Workers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerStatus        `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workers) Reset() {
	*x = Workers{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workers) ProtoMessage() {}

func (x *Workers) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workers.ProtoReflect.Descriptor instead.
func (*Workers) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *Workers) GetWorkers() []*WorkerStatus {
	if x != nil {
		return x.Workers
	}
	return nil
}

type AttemptRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Generation    int64                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,3,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptRef) Reset() {
	*x = AttemptRef{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptRef) ProtoMessage() {}

func (x *AttemptRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptRef.ProtoReflect.Descriptor instead.
func (*AttemptRef) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *AttemptRef) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *AttemptRef) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *AttemptRef) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

type Renew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempts      []*AttemptRef          `protobuf:"bytes,1,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Renew) Reset() {
	*x = Renew{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Renew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Renew) ProtoMessage() {}

func (x *Renew) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Renew.ProtoReflect.Descriptor instead.
func (*Renew) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *Renew) GetAttempts() []*AttemptRef {
	if x != nil {
		return x.Attempts
	}
	return nil
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type WorkerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*WorkerFrame_Hello
	//	*WorkerFrame_Renew
	//	*WorkerFrame_Ack
	Body          isWorkerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerFrame) Reset() {
	*x = WorkerFrame{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerFrame) ProtoMessage() {}

func (x *WorkerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerFrame.ProtoReflect.Descriptor instead.
func (*WorkerFrame) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *WorkerFrame) GetBody() isWorkerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WorkerFrame) GetHello() *WorkerHello {
	if x != nil {
		if x, ok := x.Body.(*WorkerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerFrame) GetRenew() *Renew {
	if x != nil {
		if x, ok := x.Body.(*WorkerFrame_Renew); ok {
			return x.Renew
		}
	}
	return nil
}

func (x *WorkerFrame) GetAck() *CommandAck {
	if x != nil {
		if x, ok := x.Body.(*WorkerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isWorkerFrame_Body interface {
	isWorkerFrame_Body()
}

type WorkerFrame_Hello struct {
	Hello *WorkerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerFrame_Renew struct {
	Renew *Renew `protobuf:"bytes,2,opt,name=renew,proto3,oneof"`
}

type WorkerFrame_Ack struct {
	Ack *CommandAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*WorkerFrame_Hello) isWorkerFrame_Body() {}

func (*WorkerFrame_Renew) isWorkerFrame_Body() {}

func (*WorkerFrame_Ack) isWorkerFrame_Body() {}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	LeaseToken    string                 `protobuf:"bytes,4,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"`
	LeaseTtlMs    int64                  `protobuf:"varint,5,opt,name=lease_ttl_ms,json=leaseTtlMs,proto3" json:"lease_ttl_ms,omitempty"`
	DeadlineMs    int64                  `protobuf:"varint,6,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	Spec          *TaskSpec              `protobuf:"bytes,7,opt,name=spec,proto3" json:"spec,omitempty"`
	Job           *JobExecution          `protobuf:"bytes,8,opt,name=job,proto3" json:"job,omitempty"`
	Gateway       *GatewayAccess         `protobuf:"bytes,9,opt,name=gateway,proto3" json:"gateway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *Assignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Assignment) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Assignment) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Assignment) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *Assignment) GetLeaseTtlMs() int64 {
	if x != nil {
		return x.LeaseTtlMs
	}
	return 0
}

func (x *Assignment) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *Assignment) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Assignment) GetJob() *JobExecution {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *Assignment) GetGateway() *GatewayAccess {
	if x != nil {
		return x.Gateway
	}
	return nil
}

type JobExecution struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JobId               string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Stage               string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	PartitionKey        string                 `protobuf:"bytes,3,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	ScopePaths          []string               `protobuf:"bytes,4,rep,name=scope_paths,json=scopePaths,proto3" json:"scope_paths,omitempty"`
	Strategy            string                 `protobuf:"bytes,5,opt,name=strategy,proto3" json:"strategy,omitempty"`
	TemplateDigest      string                 `protobuf:"bytes,6,opt,name=template_digest,json=templateDigest,proto3" json:"template_digest,omitempty"`
	InputManifestJson   []byte                 `protobuf:"bytes,7,opt,name=input_manifest_json,json=inputManifestJson,proto3" json:"input_manifest_json,omitempty"`
	InputManifestSha256 string                 `protobuf:"bytes,8,opt,name=input_manifest_sha256,json=inputManifestSha256,proto3" json:"input_manifest_sha256,omitempty"`
	InputLimitBytes     int64                  `protobuf:"varint,9,opt,name=input_limit_bytes,json=inputLimitBytes,proto3" json:"input_limit_bytes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *JobExecution) Reset() {
	*x = JobExecution{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecution) ProtoMessage() {}

func (x *JobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecution.ProtoReflect.Descriptor instead.
func (*JobExecution) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *JobExecution) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobExecution) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *JobExecution) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *JobExecution) GetScopePaths() []string {
	if x != nil {
		return x.ScopePaths
	}
	return nil
}

func (x *JobExecution) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *JobExecution) GetTemplateDigest() string {
	if x != nil {
		return x.TemplateDigest
	}
	return ""
}

func (x *JobExecution) GetInputManifestJson() []byte {
	if x != nil {
		return x.InputManifestJson
	}
	return nil
}

func (x *JobExecution) GetInputManifestSha256() string {
	if x != nil {
		return x.InputManifestSha256
	}
	return ""
}

func (x *JobExecution) GetInputLimitBytes() int64 {
	if x != nil {
		return x.InputLimitBytes
	}
	return 0
}

type GatewayAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Route         string                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayAccess) Reset() {
	*x = GatewayAccess{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayAccess) ProtoMessage() {}

func (x *GatewayAccess) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayAccess.ProtoReflect.Descriptor instead.
func (*GatewayAccess) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *GatewayAccess) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *GatewayAccess) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GatewayAccess) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type InputArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *AttemptRef            `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputArtifactRequest) Reset() {
	*x = InputArtifactRequest{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputArtifactRequest) ProtoMessage() {}

func (x *InputArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputArtifactRequest.ProtoReflect.Descriptor instead.
func (*InputArtifactRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{22}
}

func (x *InputArtifactRequest) GetAttempt() *AttemptRef {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *InputArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Assignment    *Assignment            `protobuf:"bytes,3,opt,name=assignment,proto3" json:"assignment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Command) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

type LeaseGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptId     string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TtlMs         int64                  `protobuf:"varint,2,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrant) Reset() {
	*x = LeaseGrant{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrant) ProtoMessage() {}

func (x *LeaseGrant) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrant.ProtoReflect.Descriptor instead.
func (*LeaseGrant) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{24}
}

func (x *LeaseGrant) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *LeaseGrant) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *LeaseGrant) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerFrame_Command
	//	*ServerFrame_Lease
	Body          isServerFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *ServerFrame) GetBody() isServerFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerFrame) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *ServerFrame) GetLease() *LeaseGrant {
	if x != nil {
		if x, ok := x.Body.(*ServerFrame_Lease); ok {
			return x.Lease
		}
	}
	return nil
}

type isServerFrame_Body interface {
	isServerFrame_Body()
}

type ServerFrame_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type ServerFrame_Lease struct {
	Lease *LeaseGrant `protobuf:"bytes,2,opt,name=lease,proto3,oneof"`
}

func (*ServerFrame_Command) isServerFrame_Body() {}

func (*ServerFrame_Lease) isServerFrame_Body() {}

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attempt       *AttemptRef            `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{26}
}

func (x *ReportRequest) GetAttempt() *AttemptRef {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *ReportRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type CompleteRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Attempt          *AttemptRef            `protobuf:"bytes,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	FinalWorkerSeq   int64                  `protobuf:"varint,2,opt,name=final_worker_seq,json=finalWorkerSeq,proto3" json:"final_worker_seq,omitempty"`
	Success          bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	CleanupConfirmed bool                   `protobuf:"varint,4,opt,name=cleanup_confirmed,json=cleanupConfirmed,proto3" json:"cleanup_confirmed,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result           string                 `protobuf:"bytes,7,opt,name=result,proto3" json:"result,omitempty"`
	NativeSessionId  string                 `protobuf:"bytes,8,opt,name=native_session_id,json=nativeSessionId,proto3" json:"native_session_id,omitempty"`
	ArtifactIds      []string               `protobuf:"bytes,9,rep,name=artifact_ids,json=artifactIds,proto3" json:"artifact_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{27}
}

func (x *CompleteRequest) GetAttempt() *AttemptRef {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *CompleteRequest) GetFinalWorkerSeq() int64 {
	if x != nil {
		return x.FinalWorkerSeq
	}
	return 0
}

func (x *CompleteRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteRequest) GetCleanupConfirmed() bool {
	if x != nil {
		return x.CleanupConfirmed
	}
	return false
}

func (x *CompleteRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *CompleteRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CompleteRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CompleteRequest) GetNativeSessionId() string {
	if x != nil {
		return x.NativeSessionId
	}
	return ""
}

func (x *CompleteRequest) GetArtifactIds() []string {
	if x != nil {
		return x.ArtifactIds
	}
	return nil
}

type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{28}
}

func (x *Artifact) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Artifact) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Artifact) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Artifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Artifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Artifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Artifacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*Artifact            `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifacts) Reset() {
	*x = Artifacts{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifacts) ProtoMessage() {}

func (x *Artifacts) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifacts.ProtoReflect.Descriptor instead.
func (*Artifacts) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{29}
}

func (x *Artifacts) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{30}
}

func (x *ArtifactRef) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ArtifactRef) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type ArtifactChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Artifact              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Attempt       *AttemptRef            `protobuf:"bytes,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactChunk) Reset() {
	*x = ArtifactChunk{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactChunk) ProtoMessage() {}

func (x *ArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactChunk.ProtoReflect.Descriptor instead.
func (*ArtifactChunk) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{31}
}

func (x *ArtifactChunk) GetMetadata() *Artifact {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ArtifactChunk) GetAttempt() *AttemptRef {
	if x != nil {
		return x.Attempt
	}
	return nil
}

func (x *ArtifactChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_api_agent_v1_runtime_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_agent_v1_runtime_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_api_agent_v1_runtime_proto_rawDescGZIP(), []int{32}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_agent_v1_runtime_proto protoreflect.FileDescriptor

const file_api_agent_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/agent/v1/runtime.proto\x12\x15computecloud.agent.v1\"\a\n" +
	"\x05Empty\"\x80\x01\n" +
	"\tWorkspace\x12%\n" +
	"\x0erepository_ref\x18\x01 \x01(\tR\rrepositoryRef\x12\x1f\n" +
	"\vbase_commit\x18\x02 \x01(\tR\n" +
	"baseCommit\x12+\n" +
	"\x11isolation_profile\x18\x03 \x01(\tR\x10isolationProfile\"\x1b\n" +
	"\x05Input\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xf6\x04\n" +
	"\bTaskSpec\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x12'\n" +
	"\x0fruntime_profile\x18\x04 \x01(\tR\x0eruntimeProfile\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12%\n" +
	"\x0ecredential_ref\x18\x06 \x01(\tR\rcredentialRef\x12>\n" +
	"\tworkspace\x18\a \x01(\v2 .computecloud.agent.v1.WorkspaceR\tworkspace\x122\n" +
	"\x05input\x18\b \x01(\v2\x1c.computecloud.agent.v1.InputR\x05input\x12\x1d\n" +
	"\n" +
	"policy_ref\x18\t \x01(\tR\tpolicyRef\x123\n" +
	"\x15required_capabilities\x18\n" +
	" \x03(\tR\x14requiredCapabilities\x12\x1f\n" +
	"\vsession_ref\x18\v \x01(\tR\n" +
	"sessionRef\x12$\n" +
	"\x0eparent_task_id\x18\f \x01(\tR\fparentTaskId\x12'\n" +
	"\x0ftimeout_seconds\x18\r \x01(\x03R\x0etimeoutSeconds\x12-\n" +
	"\x12acceptance_profile\x18\x0e \x01(\tR\x11acceptanceProfile\x12\x1a\n" +
	"\bpriority\x18\x0f \x01(\x05R\bpriority\x12!\n" +
	"\fprovider_ref\x18\x10 \x01(\tR\vproviderRef\"\"\n" +
	"\aTaskRef\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xd1\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x123\n" +
	"\x04spec\x18\x04 \x01(\v2\x1f.computecloud.agent.v1.TaskSpecR\x04spec\x12\x19\n" +
	"\blast_seq\x18\x05 \x01(\x03R\alastSeq\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06result\x18\b \x01(\tR\x06result\x12\x1f\n" +
	"\vsession_ref\x18\t \x01(\tR\n" +
	"sessionRef\x12\x1b\n" +
	"\tworker_id\x18\n" +
	" \x01(\tR\bworkerId\x12\"\n" +
	"\rcreated_at_ms\x18\v \x01(\x03R\vcreatedAtMs\x12\"\n" +
	"\rupdated_at_ms\x18\f \x01(\x03R\vupdatedAtMs\x12-\n" +
	"\x12scheduling_blocker\x18\r \x01(\tR\x11schedulingBlocker\x12\x1a\n" +
	"\bexisting\x18\x0e \x01(\bR\bexisting\"D\n" +
	"\fWatchRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq\"_\n" +
	"\rCancelRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"control_id\x18\x02 \x01(\tR\tcontrolId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x90\x01\n" +
	"\x0eControlRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"control_id\x18\x02 \x01(\tR\tcontrolId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x122\n" +
	"\x05input\x18\x04 \x01(\v2\x1c.computecloud.agent.v1.InputR\x05input\"\x88\x02\n" +
	"\x05Event\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"worker_seq\x18\x05 \x01(\x03R\tworkerSeq\x12\x10\n" +
	"\x03seq\x18\x06 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12!\n" +
	"\fpayload_json\x18\b \x01(\fR\vpayloadJson\x12$\n" +
	"\x0erecorded_at_ms\x18\t \x01(\x03R\frecordedAtMs\"V\n" +
	"\x03Ack\x12\x1f\n" +
	"\vthrough_seq\x18\x01 \x01(\x03R\n" +
	"throughSeq\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9d\x03\n" +
	"\aRuntime\x12\x18\n" +
	"\aprofile\x18\x01 \x01(\tR\aprofile\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06models\x18\x03 \x03(\tR\x06models\x12 \n" +
	"\vcredentials\x18\x04 \x03(\tR\vcredentials\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\"\n" +
	"\frepositories\x18\x06 \x03(\tR\frepositories\x12\x1a\n" +
	"\bpolicies\x18\a \x03(\tR\bpolicies\x12\x1c\n" +
	"\tverifiers\x18\b \x03(\tR\tverifiers\x12^\n" +
	"\x10template_digests\x18\t \x03(\v23.computecloud.agent.v1.Runtime.TemplateDigestsEntryR\x0ftemplateDigests\x1aB\n" +
	"\x14TemplateDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x92\x01\n" +
	"\vWorkerHello\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\tR\x05epoch\x12\x14\n" +
	"\x05slots\x18\x03 \x01(\x05R\x05slots\x12:\n" +
	"\bruntimes\x18\x04 \x03(\v2\x1e.computecloud.agent.v1.RuntimeR\bruntimes\"\xcf\x01\n" +
	"\fWorkerStatus\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12\x14\n" +
	"\x05slots\x18\x03 \x01(\x05R\x05slots\x12\x16\n" +
	"\x06active\x18\x04 \x01(\x05R\x06active\x12 \n" +
	"\flast_seen_ms\x18\x05 \x01(\x03R\n" +
	"lastSeenMs\x12:\n" +
	"\bruntimes\x18\x06 \x03(\v2\x1e.computecloud.agent.v1.RuntimeR\bruntimes\"H\n" +
	"\aWorkers\x12=\n" +
	"\aworkers\x18\x01 \x03(\v2#.computecloud.agent.v1.WorkerStatusR\aworkers\"l\n" +
	"\n" +
	"AttemptRef\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x03R\n" +
	"generation\x12\x1f\n" +
	"\vlease_token\x18\x03 \x01(\tR\n" +
	"leaseToken\"F\n" +
	"\x05Renew\x12=\n" +
	"\battempts\x18\x01 \x03(\v2!.computecloud.agent.v1.AttemptRefR\battempts\"A\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\xbe\x01\n" +
	"\vWorkerFrame\x12:\n" +
	"\x05hello\x18\x01 \x01(\v2\".computecloud.agent.v1.WorkerHelloH\x00R\x05hello\x124\n" +
	"\x05renew\x18\x02 \x01(\v2\x1c.computecloud.agent.v1.RenewH\x00R\x05renew\x125\n" +
	"\x03ack\x18\x03 \x01(\v2!.computecloud.agent.v1.CommandAckH\x00R\x03ackB\x06\n" +
	"\x04body\"\xf4\x02\n" +
	"\n" +
	"Assignment\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12\x1f\n" +
	"\vlease_token\x18\x04 \x01(\tR\n" +
	"leaseToken\x12 \n" +
	"\flease_ttl_ms\x18\x05 \x01(\x03R\n" +
	"leaseTtlMs\x12\x1f\n" +
	"\vdeadline_ms\x18\x06 \x01(\x03R\n" +
	"deadlineMs\x123\n" +
	"\x04spec\x18\a \x01(\v2\x1f.computecloud.agent.v1.TaskSpecR\x04spec\x125\n" +
	"\x03job\x18\b \x01(\v2#.computecloud.agent.v1.JobExecutionR\x03job\x12>\n" +
	"\agateway\x18\t \x01(\v2$.computecloud.agent.v1.GatewayAccessR\agateway\"\xd6\x02\n" +
	"\fJobExecution\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12#\n" +
	"\rpartition_key\x18\x03 \x01(\tR\fpartitionKey\x12\x1f\n" +
	"\vscope_paths\x18\x04 \x03(\tR\n" +
	"scopePaths\x12\x1a\n" +
	"\bstrategy\x18\x05 \x01(\tR\bstrategy\x12'\n" +
	"\x0ftemplate_digest\x18\x06 \x01(\tR\x0etemplateDigest\x12.\n" +
	"\x13input_manifest_json\x18\a \x01(\fR\x11inputManifestJson\x122\n" +
	"\x15input_manifest_sha256\x18\b \x01(\tR\x13inputManifestSha256\x12*\n" +
	"\x11input_limit_bytes\x18\t \x01(\x03R\x0finputLimitBytes\"V\n" +
	"\rGatewayAccess\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n" +
	"\x05route\x18\x03 \x01(\tR\x05route\"t\n" +
	"\x14InputArtifactRequest\x12;\n" +
	"\aattempt\x18\x01 \x01(\v2!.computecloud.agent.v1.AttemptRefR\aattempt\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\"\x7f\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12A\n" +
	"\n" +
	"assignment\x18\x03 \x01(\v2!.computecloud.agent.v1.AssignmentR\n" +
	"assignment\"X\n" +
	"\n" +
	"LeaseGrant\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12\x15\n" +
	"\x06ttl_ms\x18\x02 \x01(\x03R\x05ttlMs\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"\x8c\x01\n" +
	"\vServerFrame\x12:\n" +
	"\acommand\x18\x01 \x01(\v2\x1e.computecloud.agent.v1.CommandH\x00R\acommand\x129\n" +
	"\x05lease\x18\x02 \x01(\v2!.computecloud.agent.v1.LeaseGrantH\x00R\x05leaseB\x06\n" +
	"\x04body\"\x82\x01\n" +
	"\rReportRequest\x12;\n" +
	"\aattempt\x18\x01 \x01(\v2!.computecloud.agent.v1.AttemptRefR\aattempt\x124\n" +
	"\x06events\x18\x02 \x03(\v2\x1c.computecloud.agent.v1.EventR\x06events\"\xea\x02\n" +
	"\x0fCompleteRequest\x12;\n" +
	"\aattempt\x18\x01 \x01(\v2!.computecloud.agent.v1.AttemptRefR\aattempt\x12(\n" +
	"\x10final_worker_seq\x18\x02 \x01(\x03R\x0efinalWorkerSeq\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12+\n" +
	"\x11cleanup_confirmed\x18\x04 \x01(\bR\x10cleanupConfirmed\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06result\x18\a \x01(\tR\x06result\x12*\n" +
	"\x11native_session_id\x18\b \x01(\tR\x0fnativeSessionId\x12!\n" +
	"\fartifact_ids\x18\t \x03(\tR\vartifactIds\"\xa3\x01\n" +
	"\bArtifact\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\"J\n" +
	"\tArtifacts\x12=\n" +
	"\tartifacts\x18\x01 \x03(\v2\x1f.computecloud.agent.v1.ArtifactR\tartifacts\"G\n" +
	"\vArtifactRef\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\"\x9d\x01\n" +
	"\rArtifactChunk\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.computecloud.agent.v1.ArtifactR\bmetadata\x12;\n" +
	"\aattempt\x18\x02 \x01(\v2!.computecloud.agent.v1.AttemptRefR\aattempt\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xae\t\n" +
	"\x0eRuntimeService\x12J\n" +
	"\n" +
	"SubmitTask\x12\x1f.computecloud.agent.v1.TaskSpec\x1a\x1b.computecloud.agent.v1.Task\x12F\n" +
	"\aGetTask\x12\x1e.computecloud.agent.v1.TaskRef\x1a\x1b.computecloud.agent.v1.Task\x12O\n" +
	"\n" +
	"CancelTask\x12$.computecloud.agent.v1.CancelRequest\x1a\x1b.computecloud.agent.v1.Task\x12R\n" +
	"\vWatchEvents\x12#.computecloud.agent.v1.WatchRequest\x1a\x1c.computecloud.agent.v1.Event0\x01\x12K\n" +
	"\vListWorkers\x12\x1c.computecloud.agent.v1.Empty\x1a\x1e.computecloud.agent.v1.Workers\x12N\n" +
	"\tSendInput\x12%.computecloud.agent.v1.ControlRequest\x1a\x1a.computecloud.agent.v1.Ack\x12T\n" +
	"\x0fRespondApproval\x12%.computecloud.agent.v1.ControlRequest\x1a\x1a.computecloud.agent.v1.Ack\x12Q\n" +
	"\rListArtifacts\x12\x1e.computecloud.agent.v1.TaskRef\x1a .computecloud.agent.v1.Artifacts\x12V\n" +
	"\x10DownloadArtifact\x12\".computecloud.agent.v1.ArtifactRef\x1a\x1c.computecloud.agent.v1.Chunk0\x01\x12d\n" +
	"\x15DownloadInputArtifact\x12+.computecloud.agent.v1.InputArtifactRequest\x1a\x1c.computecloud.agent.v1.Chunk0\x01\x12[\n" +
	"\rConnectWorker\x12\".computecloud.agent.v1.WorkerFrame\x1a\".computecloud.agent.v1.ServerFrame(\x010\x01\x12P\n" +
	"\fReportEvents\x12$.computecloud.agent.v1.ReportRequest\x1a\x1a.computecloud.agent.v1.Ack\x12U\n" +
	"\x0fCompleteAttempt\x12&.computecloud.agent.v1.CompleteRequest\x1a\x1a.computecloud.agent.v1.Ack\x12Y\n" +
	"\x0eUploadArtifact\x12$.computecloud.agent.v1.ArtifactChunk\x1a\x1f.computecloud.agent.v1.Artifact(\x01B@Z>github.com/tommyxie2026-tech/computecloud/api/agent/v1;agentv1b\x06proto3"

var (
	file_api_agent_v1_runtime_proto_rawDescOnce sync.Once
	file_api_agent_v1_runtime_proto_rawDescData []byte
)

func file_api_agent_v1_runtime_proto_rawDescGZIP() []byte {
	file_api_agent_v1_runtime_proto_rawDescOnce.Do(func() {
		file_api_agent_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agent_v1_runtime_proto_rawDesc), len(file_api_agent_v1_runtime_proto_rawDesc)))
	})
	return file_api_agent_v1_runtime_proto_rawDescData
}

var file_api_agent_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_agent_v1_runtime_proto_goTypes = []any{
	(*Empty)(nil),                // 0: computecloud.agent.v1.Empty
	(*Workspace)(nil),            // 1: computecloud.agent.v1.Workspace
	(*Input)(nil),                // 2: computecloud.agent.v1.Input
	(*TaskSpec)(nil),             // 3: computecloud.agent.v1.TaskSpec
	(*TaskRef)(nil),              // 4: computecloud.agent.v1.TaskRef
	(*Task)(nil),                 // 5: computecloud.agent.v1.Task
	(*WatchRequest)(nil),         // 6: computecloud.agent.v1.WatchRequest
	(*CancelRequest)(nil),        // 7: computecloud.agent.v1.CancelRequest
	(*ControlRequest)(nil),       // 8: computecloud.agent.v1.ControlRequest
	(*Event)(nil),                // 9: computecloud.agent.v1.Event
	(*Ack)(nil),                  // 10: computecloud.agent.v1.Ack
	(*Runtime)(nil),              // 11: computecloud.agent.v1.Runtime
	(*WorkerHello)(nil),          // 12: computecloud.agent.v1.WorkerHello
	(*WorkerStatus)(nil),         // 13: computecloud.agent.v1.WorkerStatus
	(*Workers)(nil),              // 14: computecloud.agent.v1.Workers
	(*AttemptRef)(nil),           // 15: computecloud.agent.v1.AttemptRef
	(*Renew)(nil),                // 16: computecloud.agent.v1.Renew
	(*CommandAck)(nil),           // 17: computecloud.agent.v1.CommandAck
	(*WorkerFrame)(nil),          // 18: computecloud.agent.v1.WorkerFrame
	(*Assignment)(nil),           // 19: computecloud.agent.v1.Assignment
	(*JobExecution)(nil),         // 20: computecloud.agent.v1.JobExecution
	(*GatewayAccess)(nil),        // 21: computecloud.agent.v1.GatewayAccess
	(*InputArtifactRequest)(nil), // 22: computecloud.agent.v1.InputArtifactRequest
	(*Command)(nil),              // 23: computecloud.agent.v1.Command
	(*LeaseGrant)(nil),           // 24: computecloud.agent.v1.LeaseGrant
	(*ServerFrame)(nil),          // 25: computecloud.agent.v1.ServerFrame
	(*ReportRequest)(nil),        // 26: computecloud.agent.v1.ReportRequest
	(*CompleteRequest)(nil),      // 27: computecloud.agent.v1.CompleteRequest
	(*Artifact)(nil),             // 28: computecloud.agent.v1.Artifact
	(*Artifacts)(nil),            // 29: computecloud.agent.v1.Artifacts
	(*ArtifactRef)(nil),          // 30: computecloud.agent.v1.ArtifactRef
	(*ArtifactChunk)(nil),        // 31: computecloud.agent.v1.ArtifactChunk
	(*Chunk)(nil),                // 32: computecloud.agent.v1.Chunk
	nil,                          // 33: computecloud.agent.v1.Runtime.TemplateDigestsEntry
}
var file_api_agent_v1_runtime_proto_depIdxs = []int32{
	1,  // 0: computecloud.agent.v1.TaskSpec.workspace:type_name -> computecloud.agent.v1.Workspace
	2,  // 1: computecloud.agent.v1.TaskSpec.input:type_name -> computecloud.agent.v1.Input
	3,  // 2: computecloud.agent.v1.Task.spec:type_name -> computecloud.agent.v1.TaskSpec
	2,  // 3: computecloud.agent.v1.ControlRequest.input:type_name -> computecloud.agent.v1.Input
	33, // 4: computecloud.agent.v1.Runtime.template_digests:type_name -> computecloud.agent.v1.Runtime.TemplateDigestsEntry
	11, // 5: computecloud.agent.v1.WorkerHello.runtimes:type_name -> computecloud.agent.v1.Runtime
	11, // 6: computecloud.agent.v1.WorkerStatus.runtimes:type_name -> computecloud.agent.v1.Runtime
	13, // 7: computecloud.agent.v1.Workers.workers:type_name -> computecloud.agent.v1.WorkerStatus
	15, // 8: computecloud.agent.v1.Renew.attempts:type_name -> computecloud.agent.v1.AttemptRef
	12, // 9: computecloud.agent.v1.WorkerFrame.hello:type_name -> computecloud.agent.v1.WorkerHello
	16, // 10: computecloud.agent.v1.WorkerFrame.renew:type_name -> computecloud.agent.v1.Renew
	17, // 11: computecloud.agent.v1.WorkerFrame.ack:type_name -> computecloud.agent.v1.CommandAck
	3,  // 12: computecloud.agent.v1.Assignment.spec:type_name -> computecloud.agent.v1.TaskSpec
	20, // 13: computecloud.agent.v1.Assignment.job:type_name -> computecloud.agent.v1.JobExecution
	21, // 14: computecloud.agent.v1.Assignment.gateway:type_name -> computecloud.agent.v1.GatewayAccess
	15, // 15: computecloud.agent.v1.InputArtifactRequest.attempt:type_name -> computecloud.agent.v1.AttemptRef
	19, // 16: computecloud.agent.v1.Command.assignment:type_name -> computecloud.agent.v1.Assignment
	23, // 17: computecloud.agent.v1.ServerFrame.command:type_name -> computecloud.agent.v1.Command
	24, // 18: computecloud.agent.v1.ServerFrame.lease:type_name -> computecloud.agent.v1.LeaseGrant
	15, // 19: computecloud.agent.v1.ReportRequest.attempt:type_name -> computecloud.agent.v1.AttemptRef
	9,  // 20: computecloud.agent.v1.ReportRequest.events:type_name -> computecloud.agent.v1.Event
	15, // 21: computecloud.agent.v1.CompleteRequest.attempt:type_name -> computecloud.agent.v1.AttemptRef
	28, // 22: computecloud.agent.v1.Artifacts.artifacts:type_name -> computecloud.agent.v1.Artifact
	28, // 23: computecloud.agent.v1.ArtifactChunk.metadata:type_name -> computecloud.agent.v1.Artifact
	15, // 24: computecloud.agent.v1.ArtifactChunk.attempt:type_name -> computecloud.agent.v1.AttemptRef
	3,  // 25: computecloud.agent.v1.RuntimeService.SubmitTask:input_type -> computecloud.agent.v1.TaskSpec
	4,  // 26: computecloud.agent.v1.RuntimeService.GetTask:input_type -> computecloud.agent.v1.TaskRef
	7,  // 27: computecloud.agent.v1.RuntimeService.CancelTask:input_type -> computecloud.agent.v1.CancelRequest
	6,  // 28: computecloud.agent.v1.RuntimeService.WatchEvents:input_type -> computecloud.agent.v1.WatchRequest
	0,  // 29: computecloud.agent.v1.RuntimeService.ListWorkers:input_type -> computecloud.agent.v1.Empty
	8,  // 30: computecloud.agent.v1.RuntimeService.SendInput:input_type -> computecloud.agent.v1.ControlRequest
	8,  // 31: computecloud.agent.v1.RuntimeService.RespondApproval:input_type -> computecloud.agent.v1.ControlRequest
	4,  // 32: computecloud.agent.v1.RuntimeService.ListArtifacts:input_type -> computecloud.agent.v1.TaskRef
	30, // 33: computecloud.agent.v1.RuntimeService.DownloadArtifact:input_type -> computecloud.agent.v1.ArtifactRef
	22, // 34: computecloud.agent.v1.RuntimeService.DownloadInputArtifact:input_type -> computecloud.agent.v1.InputArtifactRequest
	18, // 35: computecloud.agent.v1.RuntimeService.ConnectWorker:input_type -> computecloud.agent.v1.WorkerFrame
	26, // 36: computecloud.agent.v1.RuntimeService.ReportEvents:input_type -> computecloud.agent.v1.ReportRequest
	27, // 37: computecloud.agent.v1.RuntimeService.CompleteAttempt:input_type -> computecloud.agent.v1.CompleteRequest
	31, // 38: computecloud.agent.v1.RuntimeService.UploadArtifact:input_type -> computecloud.agent.v1.ArtifactChunk
	5,  // 39: computecloud.agent.v1.RuntimeService.SubmitTask:output_type -> computecloud.agent.v1.Task
	5,  // 40: computecloud.agent.v1.RuntimeService.GetTask:output_type -> computecloud.agent.v1.Task
	5,  // 41: computecloud.agent.v1.RuntimeService.CancelTask:output_type -> computecloud.agent.v1.Task
	9,  // 42: computecloud.agent.v1.RuntimeService.WatchEvents:output_type -> computecloud.agent.v1.Event
	14, // 43: computecloud.agent.v1.RuntimeService.ListWorkers:output_type -> computecloud.agent.v1.Workers
	10, // 44: computecloud.agent.v1.RuntimeService.SendInput:output_type -> computecloud.agent.v1.Ack
	10, // 45: computecloud.agent.v1.RuntimeService.RespondApproval:output_type -> computecloud.agent.v1.Ack
	29, // 46: computecloud.agent.v1.RuntimeService.ListArtifacts:output_type -> computecloud.agent.v1.Artifacts
	32, // 47: computecloud.agent.v1.RuntimeService.DownloadArtifact:output_type -> computecloud.agent.v1.Chunk
	32, // 48: computecloud.agent.v1.RuntimeService.DownloadInputArtifact:output_type -> computecloud.agent.v1.Chunk
	25, // 49: computecloud.agent.v1.RuntimeService.ConnectWorker:output_type -> computecloud.agent.v1.ServerFrame
	10, // 50: computecloud.agent.v1.RuntimeService.ReportEvents:output_type -> computecloud.agent.v1.Ack
	10, // 51: computecloud.agent.v1.RuntimeService.CompleteAttempt:output_type -> computecloud.agent.v1.Ack
	28, // 52: computecloud.agent.v1.RuntimeService.UploadArtifact:output_type -> computecloud.agent.v1.Artifact
	39, // [39:53] is the sub-list for method output_type
	25, // [25:39] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_agent_v1_runtime_proto_init() }
func file_api_agent_v1_runtime_proto_init() {
	if File_api_agent_v1_runtime_proto != nil {
		return
	}
	file_api_agent_v1_runtime_proto_msgTypes[18].OneofWrappers = []any{
		(*WorkerFrame_Hello)(nil),
		(*WorkerFrame_Renew)(nil),
		(*WorkerFrame_Ack)(nil),
	}
	file_api_agent_v1_runtime_proto_msgTypes[25].OneofWrappers = []any{
		(*ServerFrame_Command)(nil),
		(*ServerFrame_Lease)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agent_v1_runtime_proto_rawDesc), len(file_api_agent_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agent_v1_runtime_proto_goTypes,
		DependencyIndexes: file_api_agent_v1_runtime_proto_depIdxs,
		MessageInfos:      file_api_agent_v1_runtime_proto_msgTypes,
	}.Build()
	File_api_agent_v1_runtime_proto = out.File
	file_api_agent_v1_runtime_proto_goTypes = nil
	file_api_agent_v1_runtime_proto_depIdxs = nil
}
