// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/agent/v1/runtime.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeService_SubmitTask_FullMethodName            = "/computecloud.agent.v1.RuntimeService/SubmitTask"
	RuntimeService_GetTask_FullMethodName               = "/computecloud.agent.v1.RuntimeService/GetTask"
	RuntimeService_CancelTask_FullMethodName            = "/computecloud.agent.v1.RuntimeService/CancelTask"
	RuntimeService_WatchEvents_FullMethodName           = "/computecloud.agent.v1.RuntimeService/WatchEvents"
	RuntimeService_ListWorkers_FullMethodName           = "/computecloud.agent.v1.RuntimeService/ListWorkers"
	RuntimeService_SendInput_FullMethodName             = "/computecloud.agent.v1.RuntimeService/SendInput"
	RuntimeService_RespondApproval_FullMethodName       = "/computecloud.agent.v1.RuntimeService/RespondApproval"
	RuntimeService_ListArtifacts_FullMethodName         = "/computecloud.agent.v1.RuntimeService/ListArtifacts"
	RuntimeService_DownloadArtifact_FullMethodName      = "/computecloud.agent.v1.RuntimeService/DownloadArtifact"
	RuntimeService_DownloadInputArtifact_FullMethodName = "/computecloud.agent.v1.RuntimeService/DownloadInputArtifact"
	RuntimeService_ConnectWorker_FullMethodName         = "/computecloud.agent.v1.RuntimeService/ConnectWorker"
	RuntimeService_ReportEvents_FullMethodName          = "/computecloud.agent.v1.RuntimeService/ReportEvents"
	RuntimeService_CompleteAttempt_FullMethodName       = "/computecloud.agent.v1.RuntimeService/CompleteAttempt"
	RuntimeService_UploadArtifact_FullMethodName        = "/computecloud.agent.v1.RuntimeService/UploadArtifact"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeServiceClient interface {
	SubmitTask(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *TaskRef, opts ...grpc.CallOption) (*Task, error)
	CancelTask(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*Task, error)
	WatchEvents(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	ListWorkers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Workers, error)
	SendInput(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*Ack, error)
	RespondApproval(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*Ack, error)
	ListArtifacts(ctx context.Context, in *TaskRef, opts ...grpc.CallOption) (*Artifacts, error)
	DownloadArtifact(ctx context.Context, in *ArtifactRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	DownloadInputArtifact(ctx context.Context, in *InputArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	ConnectWorker(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerFrame, ServerFrame], error)
	ReportEvents(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*Ack, error)
	CompleteAttempt(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*Ack, error)
	UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArtifactChunk, Artifact], error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) SubmitTask(ctx context.Context, in *TaskSpec, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, RuntimeService_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) GetTask(ctx context.Context, in *TaskRef, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, RuntimeService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) CancelTask(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, RuntimeService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) WatchEvents(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[0], RuntimeService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_WatchEventsClient = grpc.ServerStreamingClient[Event]

func (c *runtimeServiceClient) ListWorkers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Workers, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workers)
	err := c.cc.Invoke(ctx, RuntimeService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) SendInput(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RuntimeService_SendInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) RespondApproval(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RuntimeService_RespondApproval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ListArtifacts(ctx context.Context, in *TaskRef, opts ...grpc.CallOption) (*Artifacts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Artifacts)
	err := c.cc.Invoke(ctx, RuntimeService_ListArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) DownloadArtifact(ctx context.Context, in *ArtifactRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[1], RuntimeService_DownloadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArtifactRef, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_DownloadArtifactClient = grpc.ServerStreamingClient[Chunk]

func (c *runtimeServiceClient) DownloadInputArtifact(ctx context.Context, in *InputArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[2], RuntimeService_DownloadInputArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InputArtifactRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_DownloadInputArtifactClient = grpc.ServerStreamingClient[Chunk]

func (c *runtimeServiceClient) ConnectWorker(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[3], RuntimeService_ConnectWorker_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_ConnectWorkerClient = grpc.BidiStreamingClient[WorkerFrame, ServerFrame]

func (c *runtimeServiceClient) ReportEvents(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RuntimeService_ReportEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) CompleteAttempt(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RuntimeService_CompleteAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) UploadArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArtifactChunk, Artifact], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[4], RuntimeService_UploadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArtifactChunk, Artifact]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_UploadArtifactClient = grpc.ClientStreamingClient[ArtifactChunk, Artifact]

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
type RuntimeServiceServer interface {
	SubmitTask(context.Context, *TaskSpec) (*Task, error)
	GetTask(context.Context, *TaskRef) (*Task, error)
	CancelTask(context.Context, *CancelRequest) (*Task, error)
	WatchEvents(*WatchRequest, grpc.ServerStreamingServer[Event]) error
	ListWorkers(context.Context, *Empty) (*Workers, error)
	SendInput(context.Context, *ControlRequest) (*Ack, error)
	RespondApproval(context.Context, *ControlRequest) (*Ack, error)
	ListArtifacts(context.Context, *TaskRef) (*Artifacts, error)
	DownloadArtifact(*ArtifactRef, grpc.ServerStreamingServer[Chunk]) error
	DownloadInputArtifact(*InputArtifactRequest, grpc.ServerStreamingServer[Chunk]) error
	ConnectWorker(grpc.BidiStreamingServer[WorkerFrame, ServerFrame]) error
	ReportEvents(context.Context, *ReportRequest) (*Ack, error)
	CompleteAttempt(context.Context, *CompleteRequest) (*Ack, error)
	UploadArtifact(grpc.ClientStreamingServer[ArtifactChunk, Artifact]) error
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) SubmitTask(context.Context, *TaskSpec) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedRuntimeServiceServer) GetTask(context.Context, *TaskRef) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedRuntimeServiceServer) CancelTask(context.Context, *CancelRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedRuntimeServiceServer) WatchEvents(*WatchRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedRuntimeServiceServer) ListWorkers(context.Context, *Empty) (*Workers, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedRuntimeServiceServer) SendInput(context.Context, *ControlRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendInput not implemented")
}
func (UnimplementedRuntimeServiceServer) RespondApproval(context.Context, *ControlRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method RespondApproval not implemented")
}
func (UnimplementedRuntimeServiceServer) ListArtifacts(context.Context, *TaskRef) (*Artifacts, error) {
	return nil, status.Error(codes.Unimplemented, "method ListArtifacts not implemented")
}
func (UnimplementedRuntimeServiceServer) DownloadArtifact(*ArtifactRef, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadArtifact not implemented")
}
func (UnimplementedRuntimeServiceServer) DownloadInputArtifact(*InputArtifactRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadInputArtifact not implemented")
}
func (UnimplementedRuntimeServiceServer) ConnectWorker(grpc.BidiStreamingServer[WorkerFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method ConnectWorker not implemented")
}
func (UnimplementedRuntimeServiceServer) ReportEvents(context.Context, *ReportRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedRuntimeServiceServer) CompleteAttempt(context.Context, *CompleteRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteAttempt not implemented")
}
func (UnimplementedRuntimeServiceServer) UploadArtifact(grpc.ClientStreamingServer[ArtifactChunk, Artifact]) error {
	return status.Error(codes.Unimplemented, "method UploadArtifact not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).SubmitTask(ctx, req.(*TaskSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).GetTask(ctx, req.(*TaskRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).CancelTask(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_WatchEventsServer = grpc.ServerStreamingServer[Event]

func _RuntimeService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ListWorkers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_SendInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).SendInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_SendInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).SendInput(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_RespondApproval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).RespondApproval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_RespondApproval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).RespondApproval(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ListArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ListArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ListArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ListArtifacts(ctx, req.(*TaskRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_DownloadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ArtifactRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).DownloadArtifact(m, &grpc.GenericServerStream[ArtifactRef, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_DownloadArtifactServer = grpc.ServerStreamingServer[Chunk]

func _RuntimeService_DownloadInputArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InputArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).DownloadInputArtifact(m, &grpc.GenericServerStream[InputArtifactRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_DownloadInputArtifactServer = grpc.ServerStreamingServer[Chunk]

func _RuntimeService_ConnectWorker_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServiceServer).ConnectWorker(&grpc.GenericServerStream[WorkerFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_ConnectWorkerServer = grpc.BidiStreamingServer[WorkerFrame, ServerFrame]

func _RuntimeService_ReportEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ReportEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ReportEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ReportEvents(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_CompleteAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).CompleteAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_CompleteAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).CompleteAttempt(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_UploadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServiceServer).UploadArtifact(&grpc.GenericServerStream[ArtifactChunk, Artifact]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_UploadArtifactServer = grpc.ClientStreamingServer[ArtifactChunk, Artifact]

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "computecloud.agent.v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _RuntimeService_SubmitTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _RuntimeService_GetTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _RuntimeService_CancelTask_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _RuntimeService_ListWorkers_Handler,
		},
		{
			MethodName: "SendInput",
			Handler:    _RuntimeService_SendInput_Handler,
		},
		{
			MethodName: "RespondApproval",
			Handler:    _RuntimeService_RespondApproval_Handler,
		},
		{
			MethodName: "ListArtifacts",
			Handler:    _RuntimeService_ListArtifacts_Handler,
		},
		{
			MethodName: "ReportEvents",
			Handler:    _RuntimeService_ReportEvents_Handler,
		},
		{
			MethodName: "CompleteAttempt",
			Handler:    _RuntimeService_CompleteAttempt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _RuntimeService_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadArtifact",
			Handler:       _RuntimeService_DownloadArtifact_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadInputArtifact",
			Handler:       _RuntimeService_DownloadInputArtifact_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ConnectWorker",
			Handler:       _RuntimeService_ConnectWorker_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadArtifact",
			Handler:       _RuntimeService_UploadArtifact_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/agent/v1/runtime.proto",
}
